proxyOrder: 0
systemTheme: true
showNotifications: true
selectAfterUpdated: false
interfaceName: ""
fontFamily: ÊÄùÊ∫êÈªë‰Ωì
bypassText: |
  bypass:
    # ÂÖ∂‰ªñ
    - "*.geforce.com"
    - "*.nvidia.com"
    - "*.launchdarkly.com"
    - "*.423down.com"
    - "*.bitwarden.com"
    - "*.chaipip.com"
    - "*.hrtsea.com"
    - "*.laomo.me"
    - "*.mpyit.com"
    # ÂæÆËΩØ
    - "*.azureedge.*"
    - "*.office365.com"
    - "*.xboxlive.com"
    - "*.s-microsoft.com"
    - "*.office.com"
    - "*.live.com"
    - "*.microsoft.net"
    - "*.microsoft.com"
    - "aka.ms"
    - "*.msftauth.net"
    - "*.msft*.com"
    - "*.msauth.net"
    - "*.xbox.com"
    - "*.onestore.ms"
    #- "*.akamized.com"
    - "*.windows.net"
    - "*.windows.com"
    - "*.windowsupdate.com"
    - "*.msedge.net"
    - "*.bing.com"
    - "*.msecnd.com"
    - "*.msecnd.net"
    - "*.visualstudio.com"
    - "*.microsoftonline.com"
    # CNÂüüÂêçÁõ¥Ëøû
    - "*.cn"
    - "*.‰∏≠ÂõΩ"
    - "*.ÂÖ¨Âè∏"
    - "*.ÁΩëÁªú"
    # ‰∏≠ÂõΩÂõΩÂÜÖÂ∏∏ËßÅÂüüÂêçÂÖ≥ÈîÆËØçÁõ¥Ëøû
    - "*-cn*"
    - "*360buy*"
    - "*alicdn*"
    - "*alimama*"
    - "*alipay*"
    - "*appzapp*"
    - "*baidupcs*"
    - "*bilibili*"
    - "*ccgslb*"
    - "*chinacache*"
    - "*duobao*"
    - "*duolingo*"
    - "*jdpay*"
    - "*moke*"
    - "*qhimg*"
    - "*vpimg*"
    - "*xiami*"
    - "*xiaomi*"
    # 360
    - "*.360.com"
    - "*.360kuai.com"
    - "*.360safe.com"
    - "*.dhrest.com"
    - "*.qhres.com"
    - "*.qhstatic.com"
    - "*.qhupdate.com"
    - "*.so.com"
    # 4399
    - "*.4399.com"
    - "*.4399pk.com"
    - "*.5054399.com"
    - "*.img4399.com"
    # 58
    - "*.58.com"
    # Alibaba
    - "*.1688.com"
    - "*.aliapp.org"
    - "*.alibaba.com"
    - "*.alibabacloud.com"
    - "*.alibabausercontent.com"
    - "*.alicdn.com"
    - "*.aliexpress.com"
    - "*.aliimg.com"
    - "*.alikunlun.com"
    - "*.alipay.com"
    - "*.alipayobjects.com"
    - "*.alisoft.com"
    - "*.aliyun.com"
    - "*.aliyuncdn.com"
    - "*.aliyuncs.com"
    - "*.amap.com"
    - "*.autonavi.com"
    - "*.dingtalk.com"
    - "*.ele.me"
    - "*.hichina.com"
    - "*.mmstat.com"
    - "*.mxhichina.com"
    - "*.soku.com"
    - "*.taobao.com"
    - "*.taobaocdn.com"
    - "*.tbcache.com"
    - "*.tbcdn.com"
    - "*.tmall.com"
    - "*.tmall.hk"
    - "*.ucweb.com"
    - "*.xiami.com"
    - "*.xiami.net"
    - "*.ykimg.com"
    - "*.youku.com"
    # Baidu
    - "*.baidu.com"
    - "*.baidubcr.com"
    - "*.baidupcs.com"
    - "*.baidustatic.com"
    - "*.bcebos.com"
    - "*.bdimg.com"
    - "*.bdstatic.com"
    - "*.bdurl.net"
    - "*.hao123.com"
    - "*.hao123img.com"
    - "*.jomodns.com"
    - "*.yunjiasu-cdn.net"
    # Bilibili
    - "*.acg.tv"
    - "*.acgvideo.com"
    - "*.b23.tv"
    - "*.biliapi.com"
    - "*.biliapi.net"
    - "*.biligame.com"
    - "*.biligame.net"
    - "*.bilivideo.com"
    - "*.hdslb.com"
    - "*.im9.com"
    # Blizzard
    - "*.battle.net"
    - "*.battlenet.com"
    - "*.blizzard.com"
    # ByteDance
    - "*.bytedance.com"
    - "*.byteimg.com"
    - "*.feiliao.com"
    - "*.gifshow.com"
    - "*.huoshan.com"
    - "*.iesdouyin.com"
    - "*.ixigua.com"
    - "*.kaishou.com"
    - "*.kspkg.com"
    - "*.pstatp.com"
    - "*.snssdk.com"
    - "*.toutiao.com"
    - "*.yximgs.com"
    # CCTV
    - "*.cctv.com"
    - "*.cctvpic.com"
    - "*.livechina.com"
    # ChinaNet
    - "*.21cn.com"
    # DiDi
    - "*.didialift.com"
    - "*.didiglobal.com"
    - "*.udache.com"
    # Douyu ÊñóÈ±º
    - "*.douyu.com"
    - "*.douyu.tv"
    - "*.douyutv.com"
    # Epic
    - "*.epicgames.com"
    - "*.helpshift.com"
    - "*.paragon.com"
    - "*.unrealengine.com"
    # HuaWei
    - "*.dbankcdn.com"
    - "*.hc-cdn.com"
    - "*.hicloud.com"
    - "*.huawei.com"
    - "*.huaweicloud.com"
    - "*.huaweishop.net"
    - "*.hwccpc.com"
    - "*.vmall.com"
    - "*.vmallres.com"
    # Iflytek ÁßëÂ§ßËÆØÈ£û
    - "*.iflyink.com"
    - "*.iflyrec.com"
    - "*.iflytek.com"
    # Iqiyi
    - "*.71.am"
    - "*.71edge.com"
    - "*.iqiyi.com"
    - "*.iqiyipic.com"
    - "*.ppsimg.com"
    - "*.qiyi.com"
    - "*.qiyipic.com"
    - "*.qy.net"
    # JD
    - "*.360buy.com"
    - "*.360buyimg.com"
    - "*.jcloudcs.com"
    - "*.jd.com"
    - "*.jd.hk"
    - "*.jdcloud.com"
    - "*.jdpay.com"
    - "*.paipai.com"
    # Kingsoft
    - "*.iciba.com"
    - "*.ksosoft.com"
    - "*.ksyun.com"
    # Meitu
    - "*.meitu.com"
    - "*.meitudata.com"
    - "*.meitustat.com"
    - "*.meipai.com"
    # LeTV ‰πêËßÜ
    - "*.le.com"
    - "*.lecloud.com"
    - "*.letv.com"
    - "*.letvcloud.com"
    - "*.letvimg.com"
    - "*.letvlive.com"
    - "*.letvstore.com"
    # MGTV ËäíÊûúTV
    - "*.hitv.com"
    - "*.hunantv.com"
    - "*.mgtv.com"
    # MI
    - "*.duokan.com"
    - "*.mi-img.com"
    - "*.mi.com"
    - "*.miui.com"
    - "*.xiaomi.com"
    - "*.xiaomi.net"
    - "*.xiaomicp.com"
    # NetEase
    - "*.126.com"
    - "*.126.net"
    - "*.127.net"
    - "*.163.com"
    - "*.163yun.com"
    - "*.lofter.com"
    - "*.netease.com"
    - "*.ydstatic.com"
    - "*.youdao.com"
    # PPTV„ÄÅPPLive
    - "*.pplive.com"
    - "*.pptv.com"
    # PDD ÊãºÂ§öÂ§ö
    - "*.pinduoduo.com"
    - "*.yangkeduo.com"
    # Sina
    - "*.leju.com"
    - "*.miaopai.com"
    - "*.sina.com"
    - "*.sinaapp.com"
    - "*.sinaimg.com"
    - "*.weibo.com"
    - "*.weibocdn.com"
    - "*.xiaoka.tv"
    # Sohu Sogo
    - "*.go2map.com"
    - "*.sogo.com"
    - "*.sogou.com"
    - "*.sogoucdn.com"
    - "*.sohu-inc.com"
    - "*.sohu.com"
    - "*.sohucs.com"
    - "*.sohuno.com"
    - "*.sohurdc.com"
    - "*.v-56.com"
    # Sony
    - "*.playstation.com"
    - "*.playstation.net"
    - "*.playstationnetwork.com"
    - "*.sony.com"
    - "*.sonyentertainmentnetwork.com"
    # Spark
    - "*.amplitude.com"
    - "*.firebaseio.com"
    - "*.hockeyapp.net"
    - "*.smartmailcloud.com"
    # Steam
    - "*.steam-chat.com"
    - "*.steamgames.com"
    - "*.steamusercontent.com"
    - "*.steamcontent.com"
    - "*.steamstatic.com"
    - "*.steamcdn-a.akamaihd.net"
    - "*.steamstat.us"
    - "*.steampowered.com"
    # Tencent
    - "*.myqcloud.com"
    - "*.foxmail.com"
    - "*.gtimg.com"
    - "*.idqqimg.com"
    - "*.igamecj.com"
    - "*.myapp.com"
    - "*.myqcloud.com"
    - "*.qq.com"
    - "*.qqmail.com"
    - "*.qqurl.com"
    - "*.smtcdns.com"
    - "*.smtcdns.net"
    - "*.soso.com"
    - "*.tencent-cloud.net"
    - "*.tencent.com"
    - "*.tencentmind.com"
    - "*.tenpay.com"
    - "*.wechat.com"
    - "*.weixin.com"
    - "*.weiyun.com"
    # Vip ÂîØÂìÅ‰ºö
    - "*.appsimg.com"
    - "*.appvipshop.com"
    - "*.vip.com"
    - "*.vipstatic.com"
    # Ximalaya ÂñúÈ©¨ÊãâÈõÖ
    - "*.ximalaya.com"
    - "*.xmcdn.com"
    # Xunlei ËøÖÈõ∑
    - "*.00cdn.com"
    - "*.88cdn.com"
    - "*.kanimg.com"
    - "*.kankan.com"
    - "*.p2cdn.com"
    - "*.sandai.net"
    - "*.thundercdn.com"
    - "*.xunlei.com"
    # YYeTs ‰∫∫‰∫∫ÂΩ±ËßÜ
    - "*.got001.com"
    - "*.jstucdn.com"
    - "*.zimuzu.io"
    - "*.zimuzu.tv"
    - "*.zmz001.com"
    - "*.zmz002.com"
    - "*.zmz003.com"
    - "*.zmz004.com"
    - "*.zmz2019.com"
    - "*.zmzapi.com"
    - "*.zmzapi.net"
    - "*.zmzfile.com"
    # Private Tracker
    - "*announce*"
    - "*torrent*"
    - "*tracker*"
    - "*.animetorrents.me"
    - "*.awesome-hd.me"
    - "*.beitai.pt"
    - "*.bittorrent.com"
    - "*.broadcasthe.net"
    - "*.chdbits.co"
    - "*.classix-unlimited.co.uk"
    - "*.empornium.me"
    - "*.gazellegames.net"
    - "*.hd4fans.org"
    - "*.hdchina.org"
    - "*.hdhome.org"
    - "*.hdsky.me"
    - "*.hdtime.org"
    - "*.hdzone.me"
    - "*.icetorrent.org"
    - "*.jpopsuki.eu"
    - "*.keepfrds.com"
    - "*.leaguehd.com"
    - "*.m-team.cc"
    - "*.madsrevolution.net"
    - "*.msg.vg"
    - "*.nanyangpt.com"
    - "*.ncore.cc"
    - "*.open.cd"
    - "*.ourbits.club"
    - "*.passthepopcorn.me"
    - "*.privatehd.to"
    - "*.pthome.net"
    - "*.redacted.ch"
    - "*.springsunday.net"
    - "*.tjupt.org"
    - "*.totheglory.im"
    - "*.trontv.com"
    # TeamViewer
    - "*.teamviewer.com"
    # Public Direct CDN ÂÖ¨ÂÖ±Áõ¥Ëøû
    - "*.baomitu.com"
    - "*.bootcss.com"
    - "*.jiasule.com"
    - "*.jsdelivr.net"
    - "*.staticfile.org"
    - "*.upaiyun.com"
    # AccelerateDirectSites
    - "*.12306.com"
    - "*.17173.com"
    - "*.17k.com"
    - "*.360doc.com"
    - "*.36kr.com"
    - "*.3dmgame.com"
    - "*.51cto.com"
    - "*.51job.com"
    - "*.51jobcdn.com"
    - "*.56.com"
    - "*.8686c.com"
    - "*.abchina.com"
    - "*.abercrombie.com"
    - "*.acfun.tv"
    - "*.air-matters.com"
    - "*.air-matters.io"
    - "*.aixifan.com"
    - "*.algocasts.io"
    - "*.babytree.com"
    - "*.babytreeimg.com"
    - "*.baicizhan.com"
    - "*.baidupan.com"
    - "*.baike.com"
    - "*.biqudu.com"
    - "*.biquge.com"
    - "*.bitauto.com"
    - "*.c-ctrip.com"
    - "*.camera360.com"
    - "*.cdnmama.com"
    - "*.chaoxing.com"
    - "*.che168.com"
    - "*.chinacache.net"
    - "*.chinaso.com"
    - "*.chinaz.com"
    - "*.chinaz.net"
    - "*.chuimg.com"
    - "*.cibntv.net"
    - "*.clouddn.com"
    - "*.cloudxns.net"
    - "*.cn163.net"
    - "*.cnbeta.com"
    - "*.cnbetacdn.com"
    - "*.cnblogs.com"
    - "*.cnki.net"
    - "*.cnmstl.net"
    - "*.coolapk.com"
    - "*.coolapkmarket.com"
    - "*.csdn.net"
    - "*.ctrip.com"
    - "*.dangdang.com"
    - "*.dfcfw.com"
    - "*.dianping.com"
    - "*.dilidili.wang"
    - "*.douban.com"
    - "*.doubanio.com"
    - "*.dpfile.com"
    - "*.duowan.com"
    - "*.dxycdn.com"
    - "*.dytt8.net"
    - "*.easou.com"
    - "*.eastday.com"
    - "*.eastmoney.com"
    - "*.ecitic.com"
    - "*.ewqcxz.com"
    - "*.fang.com"
    - "*.fantasy.tv"
    - "*.feng.com"
    - "*.fengkongcloud.com"
    - "*.fir.im"
    - "*.frdic.com"
    - "*.fresh-ideas.cc"
    - "*.ganji.com"
    - "*.ganjistatic1.com"
    - "*.geetest.com"
    - "*.geilicdn.com"
    - "*.godic.net"
    - "*.gravatar.com"
    - "*.guazi.com"
    - "*.gwdang.com"
    - "*.gzlzfm.com"
    - "*.haibian.com"
    - "*.haosou.com"
    - "*.hollisterco.com"
    - "*.hongxiu.com"
    - "*.huajiao.com"
    - "*.hupu.com"
    - "*.huxiucdn.com"
    - "*.huya.com"
    - "*.ifeng.com"
    - "*.ifengimg.com"
    - "*.images-amazon.com"
    - "*.infzm.com"
    - "*.ipip.net"
    - "*.it168.com"
    - "*.ithome.com"
    - "*.ixdzs.com"
    - "*.jianguoyun.com"
    - "*.jianshu.com"
    - "*.jianshu.io"
    - "*.jianshuapi.com"
    - "*.jiathis.com"
    - "*.jmstatic.com"
    - "*.jumei.com"
    - "*.kaola.com"
    - "*.knewone.com"
    - "*.koowo.com"
    - "*.ksyungslb.com"
    - "*.kuaidi100.com"
    - "*.kugou.com"
    - "*.lancdns.com"
    - "*.landiannews.com"
    - "*.lanzou.com"
    - "*.lemicp.com"
    - "*.letitfly.me"
    - "*.linkedin.com"
    - "*.lizhi.fm"
    - "*.lizhi.io"
    - "*.lizhifm.com"
    - "*.loli.net"
    - "*.luoo.net"
    - "*.lvmama.com"
    - "*.lxdns.com"
    - "*.maoyan.com"
    - "*.meilishuo.com"
    - "*.meituan.com"
    - "*.meituan.net"
    - "*.meizu.com"
    - "*.miguvideo.com"
    - "*.mobike.com"
    - "*.mogu.com"
    - "*.mogucdn.com"
    - "*.mogujie.com"
    - "*.moji.com"
    - "*.moke.com"
    - "*.msstatic.com"
    - "*.mubu.com"
    - "*.myunlu.com"
    - "*.nruan.com"
    - "*.nuomi.com"
    - "*.onedns.net"
    - "*.onlinedown.net"
    - "*.oracle.com"
    - "*.oschina.net"
    - "*.ourdvs.com"
    - "*.overcast.fm"
    - "*.paypal.com"
    - "*.polyv.net"
    - "*.qbox.me"
    - "*.qcloud.com"
    - "*.qcloudcdn.com"
    - "*.qdaily.com"
    - "*.qdmm.com"
    - "*.qhimg.com"
    - "*.qianqian.com"
    - "*.qidian.com"
    - "*.qihucdn.com"
    - "*.qin.io"
    - "*.qiniu.com"
    - "*.qiniucdn.com"
    - "*.qiniudn.com"
    - "*.qiushibaike.com"
    - "*.quanmin.tv"
    - "*.qunar.com"
    - "*.qunarzz.com"
    - "*.rarbg.to"
    - "*.repaik.com"
    - "*.rrmj.tv"
    - "*.ruguoapp.com"
    - "*.runoob.com"
    - "*.sankuai.com"
    - "*.segmentfault.com"
    - "*.sf-express.com"
    - "*.shumilou.net"
    - "*.simplecd.me"
    - "*.sm.ms"
    - "*.smzdm.com"
    - "*.snwx.com"
    - "*.soufunimg.com"
    - "*.ssl-images-amazon.com"
    - "*.sspai.com"
    - "*.startssl.com"
    - "*.suning.com"
    - "*.taihe.com"
    - "*.th-sjy.com"
    - "*.tianqi.com"
    - "*.tianqistatic.com"
    - "*.tianyancha.com"
    - "*.tianyaui.com"
    - "*.tietuku.com"
    - "*.tiexue.net"
    - "*.tmiaoo.com"
    - "*.trip.com"
    - "*.ttmeiju.com"
    - "*.tudou.com"
    - "*.tuniu.com"
    - "*.tuniucdn.com"
    - "*.umengcloud.com"
    - "*.upyun.com"
    - "*.uxengine.net"
    - "*.videocc.net"
    - "*.vmware.com"
    - "*.wandoujia.com"
    - "*.weather.com"
    - "*.weico.cc"
    - "*.weidian.com"
    - "*.weiphone.com"
    - "*.weiphone.net"
    - "*.womai.com"
    - "*.wscdns.com"
    - "*.xdrig.com"
    - "*.xhscdn.com"
    - "*.xiachufang.com"
    - "*.xiaohongshu.com"
    - "*.xiaojukeji.com"
    - "*.xinhuanet.com"
    - "*.xitek.com"
    - "*.xiumi.us"
    - "*.xslb.net"
    - "*.xueqiu.com"
    - "*.yach.me"
    - "*.yeepay.com"
    - "*.yhd.com"
    - "*.yihaodianimg.com"
    - "*.yinxiang.com"
    - "*.yinyuetai.com"
    - "*.yixia.com"
    - "*.ys168.com"
    - "*.yuewen.com"
    - "*.yy.com"
    - "*.yystatic.com"
    - "*.zealer.com"
    - "*.zhangzishi.cc"
    - "*.zhanqi.tv"
    - "*.zhaopin.com"
    - "*.zhihu.com"
    - "*.zhimg.com"
    - "*.zhongsou.com"
    - "*.zhuihd.com"
    - "localhost"
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
mixinText: |-
  mixin: # object
    dns:
      enable: true
      ipv6: true
      enhanced-mode: redir-host
      nameserver:
        - 8.8.8.8 #Ë∞∑Ê≠å
        - 8.8.4.4
        - 80.80.80.80 #freenomm
        - 80.80.81.81
        - 4.2.2.2  #ÂæÆËΩØ
        - 4.2.2.1
        - 1.2.4.8  #‰∏≠ÁßëÂ§ß
        - 223.5.5.5 #ÈòøÈáå
        - 223.6.6.6
        - 202.96.128.86 #Áîµ‰ø°dns
        - 202.96.134.33
      fallback:
        - 8.8.8.8  #Ë∞∑Ê≠å
        - 8.8.4.4
        - tls://dns.google:853
        - https://dns.google/dns-query
        - 208.67.222.222  #opendns
        - 208.67.220.220
        - 80.80.80.80 #freenomm
        - 80.80.81.81
        - 1.1.1.1  #cloudflare
        - tls://1.1.1.1:853
        - https://cloudflare-dns.com/dns-query
        - tls://dns.rubyfish.cn:853  #Á∫¢È±º
        - https://dns.rubyfish.cn/dns-query
        - tls://13800000000.rubyfish.cn:853
        - tls://223.5.5.5:853 #alidns
        - https://223.5.5.5/dns-query
        - 9.9.9.9 #qurd9
      fallback-filter:
        geoip: true # ÈªòËÆ§
        ipcidr: # Âú®Ëøô‰∏™ÁΩëÊÆµÂÜÖÁöÑ IP Âú∞ÂùÄ‰ºöË¢´ËÄÉËôë‰∏∫Ë¢´Ê±°ÊüìÁöÑ IP
          - 240.0.0.0/4
profileParsersText: >
  parsers: # array
    - reg: .*
      code: |
        module.exports.parse = (raw, { yaml, notify }) => {
          const doc = yaml.parse(raw)
          //ÂÖºÂÆπÊÄß
          if (doc['proxies'] === undefined) {
            doc['proxies'] = doc['Proxy']
            delete doc['Proxy']
            doc['proxy-groups'] = doc['Proxy Group']
            delete doc['Proxy Group']
            doc['rules'] = doc['Rule']
            delete doc['Rule']
          }
          //ËßÑÂàôÁªÑüöÄ‚öôÔ∏èüîìüëã
          for(var i = 0;i < doc['proxy-groups'].length;i++){
            if(doc['proxy-groups'][i]['name'] == 'üîìËß£ÈîÅÁΩëÊòì‰∫ëÁÅ∞Ëâ≤Ê≠åÊõ≤'){
              doc['proxy-groups'][i]['proxies'].push('üá®üá≥ UNM_Network')
              doc['proxy-groups'][i]['proxies'].push('üáØüáµ UNM-JP-PC')
              doc['proxy-groups'][i]['proxies'].push('üáØüáµ UNM-CN-HHHT-PC')
            }
            if(doc['proxy-groups'][i]['name'] == 'üëãManual'){
              doc['proxy-groups'][i]['proxies'].push('üá≠üá∞ Azure ‰∫öÊ¥≤')
              doc['proxy-groups'][i]['proxies'].push('üá∫üá∏ IBM ËææÊãâÊñØ')
            }    
          }
          //Ê∏ÖÁêÜÊó†Áî®Â≠óÂÖ∏
          delete doc['rules']
          delete doc['port']
          delete doc['socks-port']
          delete doc['mixed-port']
          delete doc['redir-port']
          delete doc['allow-lan']
          delete doc['mode']
          delete doc['log-level']
          delete doc['external-controller']
          delete doc['secret']
          delete doc['cfw-bypass']
          delete doc['cfw-latency-url']
          delete doc['cfw-conn-break-strategy']
          delete doc['cfw-child-process']
          delete doc['cfw-latency-timeout']
          delete doc['Rule']
          delete doc['Proxy Group']
          delete doc['Proxy']
          notify("profile has been updated", "Personal rules has been updated.", true)
          return yaml.stringify(doc)
        }
    - reg: .*
      file: 'C:/Users/YOURNAME/.config/clash/parser.yaml'
connProfile: true
shortcutSystemProxy: ""
shortcutMixin: ""
connMode: true
showNewVersionIcon: true
systemProxyType: 0
showProxyFilter: true
systemProxyPac: https://cdn.jsdelivr.net/gh/v2fly/domain-list-community@release/gfwlist.txt
childProcessText: |+
  processes: # array
    - command: "C:/Users/YOURNAME/.config/clash/subconverter/subconverter.exe"
      args:
        - "-cfw" # ËøêË°åÂèÇÊï∞1
        - "-f" # ËøêË°åÂèÇÊï∞2
        - "pref-new.yml" # ËøêË°åÂèÇÊï∞3
      options:
        cwd: C:/Users/YOURNAME/.config/clash/subconverter # Â≠êËøõÁ®ãÂ∑•‰ΩúÁõÆÂΩï
        windowsHide: true # ÈöêËóèÂ≠êËøõÁ®ãÁöÑÊéßÂà∂Âè∞Á™óÂè£

