proxyOrder: 2
systemTheme: true
showNotifications: true
selectAfterUpdated: false
interfaceName: ""
bypassText: |
  bypass:
    # 其他
    - "*.helanzuida.com"
    - "*.ksyna.com"
    - "*.pinyuncloud.com"
    - "*.mihoyo.com"
    - "*.bejingyongjiu.com"
    - "*.geforce.com"
    - "*.nvidia.com"
    - "*.launchdarkly.com"
    - "*.423down.com"
    - "*.bitwarden.com"
    - "*.chaipip.com"
    - "*.hrtsea.com"
    - "*.laomo.me"
    - "*.mpyit.com"
    # 微软
    - "*.azureedge.*"
    - "*.office365.com"
    - "*.xboxlive.com"
    - "*.s-microsoft.com"
    - "*.office.com"
    - "*.live.com"
    - "*.microsoft.net"
    - "*.microsoft.com"
    - "aka.ms"
    - "*.msftauth.net"
    - "*.msft*.com"
    - "*.msauth.net"
    - "*.xbox.com"
    - "*.onestore.ms"
    - "*.msn.com"
    - "config.edge.skype.com"
    #- "*.akamized.com"
    - "*.windows.net"
    - "*.windows.com"
    - "*.windowsupdate.com"
    - "*.msedge.net"
    - "*.bing.com"
    - "*.msecnd.com"
    - "*.msecnd.net"
    - "*.visualstudio.com"
    - "*.microsoftonline.com"
    # CN域名直连
    - "*.cn"
    - "*.中国"
    - "*.公司"
    - "*.网络"
    # 中国国内常见域名关键词直连
    - "*-cn*"
    - "*360buy*"
    - "*alicdn*"
    - "*alimama*"
    - "*alipay*"
    - "*appzapp*"
    - "*baidupcs*"
    - "*bilibili*"
    - "*ccgslb*"
    - "*chinacache*"
    - "*duobao*"
    - "*duolingo*"
    - "*jdpay*"
    - "*moke*"
    - "*qhimg*"
    - "*vpimg*"
    - "*xiami*"
    - "*xiaomi*"
    # 360
    - "*.360.com"
    - "*.360kuai.com"
    - "*.360safe.com"
    - "*.dhrest.com"
    - "*.qhres.com"
    - "*.qhstatic.com"
    - "*.qhupdate.com"
    - "*.so.com"
    # 4399
    - "*.4399.com"
    - "*.4399pk.com"
    - "*.5054399.com"
    - "*.img4399.com"
    # 58
    - "*.58.com"
    # Alibaba
    - "*.1688.com"
    - "*.aliapp.org"
    - "*.alibaba.com"
    - "*.alibabacloud.com"
    - "*.alibabausercontent.com"
    - "*.alicdn.com"
    - "*.aliexpress.com"
    - "*.aliimg.com"
    - "*.alikunlun.com"
    - "*.alipay.com"
    - "*.alipayobjects.com"
    - "*.alisoft.com"
    - "*.aliyun.com"
    - "*.aliyuncdn.com"
    - "*.aliyuncs.com"
    - "*.amap.com"
    - "*.autonavi.com"
    - "*.dingtalk.com"
    - "*.ele.me"
    - "*.hichina.com"
    - "*.mmstat.com"
    - "*.mxhichina.com"
    - "*.soku.com"
    - "*.taobao.com"
    - "*.taobaocdn.com"
    - "*.tbcache.com"
    - "*.tbcdn.com"
    - "*.tmall.com"
    - "*.tmall.hk"
    - "*.ucweb.com"
    - "*.xiami.com"
    - "*.xiami.net"
    - "*.ykimg.com"
    - "*.youku.com"
    # Baidu
    - "*.baidu.com"
    - "*.baidubcr.com"
    - "*.baidupcs.com"
    - "*.baidustatic.com"
    - "*.bcebos.com"
    - "*.bdimg.com"
    - "*.bdstatic.com"
    - "*.bdurl.net"
    - "*.hao123.com"
    - "*.hao123img.com"
    - "*.jomodns.com"
    - "*.yunjiasu-cdn.net"
    # Bilibili
    - "*.acg.tv"
    - "*.acgvideo.com"
    - "*.b23.tv"
    - "*.biliapi.com"
    - "*.biliapi.net"
    - "*.biligame.com"
    - "*.biligame.net"
    - "*.bilivideo.com"
    - "*.hdslb.com"
    - "*.im9.com"
    # Blizzard
    - "*.battle.net"
    - "*.battlenet.com"
    - "*.blizzard.com"
    # ByteDance
    - "*.bytedance.com"
    - "*.byteimg.com"
    - "*.feiliao.com"
    - "*.gifshow.com"
    - "*.huoshan.com"
    - "*.iesdouyin.com"
    - "*.ixigua.com"
    - "*.kaishou.com"
    - "*.kspkg.com"
    - "*.pstatp.com"
    - "*.snssdk.com"
    - "*.toutiao.com"
    - "*.yximgs.com"
    # CCTV
    - "*.cctv.com"
    - "*.cctvpic.com"
    - "*.livechina.com"
    # ChinaNet
    - "*.21cn.com"
    # DiDi
    - "*.didialift.com"
    - "*.didiglobal.com"
    - "*.udache.com"
    # Douyu 斗鱼
    - "*.douyu.com"
    - "*.douyu.tv"
    - "*.douyutv.com"
    # Epic
    - "*.epicgames.com"
    - "*.helpshift.com"
    - "*.paragon.com"
    - "*.unrealengine.com"
    # HuaWei
    - "*.dbankcdn.com"
    - "*.hc-cdn.com"
    - "*.hicloud.com"
    - "*.huawei.com"
    - "*.huaweicloud.com"
    - "*.huaweishop.net"
    - "*.hwccpc.com"
    - "*.vmall.com"
    - "*.vmallres.com"
    # Iflytek 科大讯飞
    - "*.iflyink.com"
    - "*.iflyrec.com"
    - "*.iflytek.com"
    # Iqiyi
    - "*.71.am"
    - "*.71edge.com"
    - "*.iqiyi.com"
    - "*.iqiyipic.com"
    - "*.ppsimg.com"
    - "*.qiyi.com"
    - "*.qiyipic.com"
    - "*.qy.net"
    # JD
    - "*.360buy.com"
    - "*.360buyimg.com"
    - "*.jcloudcs.com"
    - "*.jd.com"
    - "*.jd.hk"
    - "*.jdcloud.com"
    - "*.jdpay.com"
    - "*.paipai.com"
    # Kingsoft
    - "*.iciba.com"
    - "*.ksosoft.com"
    - "*.ksyun.com"
    # Meitu
    - "*.meitu.com"
    - "*.meitudata.com"
    - "*.meitustat.com"
    - "*.meipai.com"
    # LeTV 乐视
    - "*.le.com"
    - "*.lecloud.com"
    - "*.letv.com"
    - "*.letvcloud.com"
    - "*.letvimg.com"
    - "*.letvlive.com"
    - "*.letvstore.com"
    # MGTV 芒果TV
    - "*.hitv.com"
    - "*.hunantv.com"
    - "*.mgtv.com"
    # MI
    - "*.duokan.com"
    - "*.mi-img.com"
    - "*.mi.com"
    - "*.miui.com"
    - "*.xiaomi.com"
    - "*.xiaomi.net"
    - "*.xiaomicp.com"
    # NetEase
    - "*.126.com"
    - "*.126.net"
    - "*.127.net"
    - "*.163.com"
    - "*.163yun.com"
    - "*.lofter.com"
    - "*.netease.com"
    - "*.ydstatic.com"
    - "*.youdao.com"
    # PPTV、PPLive
    - "*.pplive.com"
    - "*.pptv.com"
    # PDD 拼多多
    - "*.pinduoduo.com"
    - "*.yangkeduo.com"
    # Sina
    - "*.leju.com"
    - "*.miaopai.com"
    - "*.sina.com"
    - "*.sinaapp.com"
    - "*.sinaimg.com"
    - "*.weibo.com"
    - "*.weibocdn.com"
    - "*.xiaoka.tv"
    # Sohu Sogo
    - "*.go2map.com"
    - "*.sogo.com"
    - "*.sogou.com"
    - "*.sogoucdn.com"
    - "*.sohu-inc.com"
    - "*.sohu.com"
    - "*.sohucs.com"
    - "*.sohuno.com"
    - "*.sohurdc.com"
    - "*.v-56.com"
    # Sony
    - "*.playstation.com"
    - "*.playstation.net"
    - "*.playstationnetwork.com"
    - "*.sony.com"
    - "*.sonyentertainmentnetwork.com"
    # Spark
    - "*.amplitude.com"
    - "*.firebaseio.com"
    - "*.hockeyapp.net"
    - "*.smartmailcloud.com"
    # Steam
    - "*.steam-chat.com"
    - "*.steamgames.com"
    - "*.steamusercontent.com"
    - "*.steamcontent.com"
    - "*.steamstatic.com"
    - "*.steamcdn-a.akamaihd.net"
    - "*.steamstat.us"
    - "*.steampowered.com"
    # Tencent
    - "*.myqcloud.com"
    - "*.foxmail.com"
    - "*.gtimg.com"
    - "*.idqqimg.com"
    - "*.igamecj.com"
    - "*.myapp.com"
    - "*.myqcloud.com"
    - "*.qq.com"
    - "*.qqmail.com"
    - "*.qqurl.com"
    - "*.smtcdns.com"
    - "*.smtcdns.net"
    - "*.soso.com"
    - "*.tencent-cloud.net"
    - "*.tencent.com"
    - "*.tencentmind.com"
    - "*.tenpay.com"
    - "*.wechat.com"
    - "*.weixin.com"
    - "*.weiyun.com"
    # Vip 唯品会
    - "*.appsimg.com"
    - "*.appvipshop.com"
    - "*.vip.com"
    - "*.vipstatic.com"
    # Ximalaya 喜马拉雅
    - "*.ximalaya.com"
    - "*.xmcdn.com"
    # Xunlei 迅雷
    - "*.00cdn.com"
    - "*.88cdn.com"
    - "*.kanimg.com"
    - "*.kankan.com"
    - "*.p2cdn.com"
    - "*.sandai.net"
    - "*.thundercdn.com"
    - "*.xunlei.com"
    # YYeTs 人人影视
    - "*.got001.com"
    - "*.jstucdn.com"
    - "*.zimuzu.io"
    - "*.zimuzu.tv"
    - "*.zmz001.com"
    - "*.zmz002.com"
    - "*.zmz003.com"
    - "*.zmz004.com"
    - "*.zmz2019.com"
    - "*.zmzapi.com"
    - "*.zmzapi.net"
    - "*.zmzfile.com"
    # Private Tracker
    - "*announce*"
    - "*torrent*"
    - "*tracker*"
    - "*.animetorrents.me"
    - "*.awesome-hd.me"
    - "*.beitai.pt"
    - "*.bittorrent.com"
    - "*.broadcasthe.net"
    - "*.chdbits.co"
    - "*.classix-unlimited.co.uk"
    - "*.empornium.me"
    - "*.gazellegames.net"
    - "*.hd4fans.org"
    - "*.hdchina.org"
    - "*.hdhome.org"
    - "*.hdsky.me"
    - "*.hdtime.org"
    - "*.hdzone.me"
    - "*.icetorrent.org"
    - "*.jpopsuki.eu"
    - "*.keepfrds.com"
    - "*.leaguehd.com"
    - "*.m-team.cc"
    - "*.madsrevolution.net"
    - "*.msg.vg"
    - "*.nanyangpt.com"
    - "*.ncore.cc"
    - "*.open.cd"
    - "*.ourbits.club"
    - "*.passthepopcorn.me"
    - "*.privatehd.to"
    - "*.pthome.net"
    - "*.redacted.ch"
    - "*.springsunday.net"
    - "*.tjupt.org"
    - "*.totheglory.im"
    - "*.trontv.com"
    # TeamViewer
    - "*.teamviewer.com"
    # Public Direct CDN 公共直连
    - "*.baomitu.com"
    - "*.bootcss.com"
    - "*.jiasule.com"
    - "*.jsdelivr.net"
    - "*.staticfile.org"
    - "*.upaiyun.com"
    # AccelerateDirectSites
    - "*.12306.com"
    - "*.17173.com"
    - "*.17k.com"
    - "*.360doc.com"
    - "*.36kr.com"
    - "*.3dmgame.com"
    - "*.51cto.com"
    - "*.51job.com"
    - "*.51jobcdn.com"
    - "*.56.com"
    - "*.8686c.com"
    - "*.abchina.com"
    - "*.abercrombie.com"
    - "*.acfun.tv"
    - "*.air-matters.com"
    - "*.air-matters.io"
    - "*.aixifan.com"
    - "*.algocasts.io"
    - "*.babytree.com"
    - "*.babytreeimg.com"
    - "*.baicizhan.com"
    - "*.baidupan.com"
    - "*.baike.com"
    - "*.biqudu.com"
    - "*.biquge.com"
    - "*.bitauto.com"
    - "*.c-ctrip.com"
    - "*.camera360.com"
    - "*.cdnmama.com"
    - "*.chaoxing.com"
    - "*.che168.com"
    - "*.chinacache.net"
    - "*.chinaso.com"
    - "*.chinaz.com"
    - "*.chinaz.net"
    - "*.chuimg.com"
    - "*.cibntv.net"
    - "*.clouddn.com"
    - "*.cloudxns.net"
    - "*.cn163.net"
    - "*.cnbeta.com"
    - "*.cnbetacdn.com"
    - "*.cnblogs.com"
    - "*.cnki.net"
    - "*.cnmstl.net"
    - "*.coolapk.com"
    - "*.coolapkmarket.com"
    - "*.csdn.net"
    - "*.ctrip.com"
    - "*.dangdang.com"
    - "*.dfcfw.com"
    - "*.dianping.com"
    - "*.dilidili.wang"
    - "*.douban.com"
    - "*.doubanio.com"
    - "*.dpfile.com"
    - "*.duowan.com"
    - "*.dxycdn.com"
    - "*.dytt8.net"
    - "*.easou.com"
    - "*.eastday.com"
    - "*.eastmoney.com"
    - "*.ecitic.com"
    - "*.ewqcxz.com"
    - "*.fang.com"
    - "*.fantasy.tv"
    - "*.feng.com"
    - "*.fengkongcloud.com"
    - "*.fir.im"
    - "*.frdic.com"
    - "*.fresh-ideas.cc"
    - "*.ganji.com"
    - "*.ganjistatic1.com"
    - "*.geetest.com"
    - "*.geilicdn.com"
    - "*.godic.net"
    - "*.gravatar.com"
    - "*.guazi.com"
    - "*.gwdang.com"
    - "*.gzlzfm.com"
    - "*.haibian.com"
    - "*.haosou.com"
    - "*.hollisterco.com"
    - "*.hongxiu.com"
    - "*.huajiao.com"
    - "*.hupu.com"
    - "*.huxiucdn.com"
    - "*.huya.com"
    - "*.ifeng.com"
    - "*.ifengimg.com"
    - "*.images-amazon.com"
    - "*.infzm.com"
    - "*.ipip.net"
    - "*.it168.com"
    - "*.ithome.com"
    - "*.ixdzs.com"
    - "*.jianguoyun.com"
    - "*.jianshu.com"
    - "*.jianshu.io"
    - "*.jianshuapi.com"
    - "*.jiathis.com"
    - "*.jmstatic.com"
    - "*.jumei.com"
    - "*.kaola.com"
    - "*.knewone.com"
    - "*.koowo.com"
    - "*.ksyungslb.com"
    - "*.kuaidi100.com"
    - "*.kugou.com"
    - "*.lancdns.com"
    - "*.landiannews.com"
    - "*.lanzou.com"
    - "*.lemicp.com"
    - "*.letitfly.me"
    - "*.linkedin.com"
    - "*.lizhi.fm"
    - "*.lizhi.io"
    - "*.lizhifm.com"
    - "*.loli.net"
    - "*.luoo.net"
    - "*.lvmama.com"
    - "*.lxdns.com"
    - "*.maoyan.com"
    - "*.meilishuo.com"
    - "*.meituan.com"
    - "*.meituan.net"
    - "*.meizu.com"
    - "*.miguvideo.com"
    - "*.mobike.com"
    - "*.mogu.com"
    - "*.mogucdn.com"
    - "*.mogujie.com"
    - "*.moji.com"
    - "*.moke.com"
    - "*.msstatic.com"
    - "*.mubu.com"
    - "*.myunlu.com"
    - "*.nruan.com"
    - "*.nuomi.com"
    - "*.onedns.net"
    - "*.onlinedown.net"
    - "*.oracle.com"
    - "*.oschina.net"
    - "*.ourdvs.com"
    - "*.overcast.fm"
    - "*.paypal.com"
    - "*.polyv.net"
    - "*.qbox.me"
    - "*.qcloud.com"
    - "*.qcloudcdn.com"
    - "*.qdaily.com"
    - "*.qdmm.com"
    - "*.qhimg.com"
    - "*.qianqian.com"
    - "*.qidian.com"
    - "*.qihucdn.com"
    - "*.qin.io"
    - "*.qiniu.com"
    - "*.qiniucdn.com"
    - "*.qiniudn.com"
    - "*.qiushibaike.com"
    - "*.quanmin.tv"
    - "*.qunar.com"
    - "*.qunarzz.com"
    - "*.rarbg.to"
    - "*.repaik.com"
    - "*.rrmj.tv"
    - "*.ruguoapp.com"
    - "*.runoob.com"
    - "*.sankuai.com"
    - "*.segmentfault.com"
    - "*.sf-express.com"
    - "*.shumilou.net"
    - "*.simplecd.me"
    - "*.sm.ms"
    - "*.smzdm.com"
    - "*.snwx.com"
    - "*.soufunimg.com"
    - "*.ssl-images-amazon.com"
    - "*.sspai.com"
    - "*.startssl.com"
    - "*.suning.com"
    - "*.taihe.com"
    - "*.th-sjy.com"
    - "*.tianqi.com"
    - "*.tianqistatic.com"
    - "*.tianyancha.com"
    - "*.tianyaui.com"
    - "*.tietuku.com"
    - "*.tiexue.net"
    - "*.tmiaoo.com"
    - "*.trip.com"
    - "*.ttmeiju.com"
    - "*.tudou.com"
    - "*.tuniu.com"
    - "*.tuniucdn.com"
    - "*.umengcloud.com"
    - "*.upyun.com"
    - "*.uxengine.net"
    - "*.videocc.net"
    - "*.vmware.com"
    - "*.wandoujia.com"
    - "*.weather.com"
    - "*.weico.cc"
    - "*.weidian.com"
    - "*.weiphone.com"
    - "*.weiphone.net"
    - "*.womai.com"
    - "*.wscdns.com"
    - "*.xdrig.com"
    - "*.xhscdn.com"
    - "*.xiachufang.com"
    - "*.xiaohongshu.com"
    - "*.xiaojukeji.com"
    - "*.xinhuanet.com"
    - "*.xitek.com"
    - "*.xiumi.us"
    - "*.xslb.net"
    - "*.xueqiu.com"
    - "*.yach.me"
    - "*.yeepay.com"
    - "*.yhd.com"
    - "*.yihaodianimg.com"
    - "*.yinxiang.com"
    - "*.yinyuetai.com"
    - "*.yixia.com"
    - "*.ys168.com"
    - "*.yuewen.com"
    - "*.yy.com"
    - "*.yystatic.com"
    - "*.zealer.com"
    - "*.zhangzishi.cc"
    - "*.zhanqi.tv"
    - "*.zhaopin.com"
    - "*.zhihu.com"
    - "*.zhimg.com"
    - "*.zhongsou.com"
    - "*.zhuihd.com"
    - "localhost"
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
mixinText: |-
  mixin: # object
    dns:
      enable: true
      ipv6: true
      enhanced-mode: redir-host
      #listen: 0.0.0.0:53
      nameserver:
        # 大部分走的都是需要代理的，全部DoH, DoT算了
        #- 8.8.8.8 #谷歌
        #- 8.8.4.4
        #- 80.80.80.80 #freenomm
        #- 80.80.81.81
        #- 4.2.2.2  #微软
        #- 4.2.2.1
        #- 1.2.4.8  #中科大
        #- 223.5.5.5 #阿里
        #- 223.6.6.6
        #- 202.96.128.86 #电信dns
        #- 202.96.134.33
        # 仅保留doh 且尽量使用ip域名
        - https://doh.opendns.com  #opendns
        #- tls://dns.google:853 #谷歌
        #- https://dns.google/dns-query
        - https://8.8.8.8/dns-query
        #- tls://1.1.1.1:853 #cloudflare
        #- https://cloudflare-dns.com/dns-query
        - https://1.1.1.1/dns-query
        #- tls://dns.rubyfish.cn:853  #红鱼
        - https://dns.rubyfish.cn/dns-query
        #- tls://223.5.5.5:853 #alidns
        - https://223.5.5.5/dns-query
        #- tls://dns.quad9.net:853 #qurd9
        #- https://dns.quad9.net/dns-query
        - https://9.9.9.9/dns-query
      fallback:
        # 仅保留doh 且尽量使用ip域名
        - https://doh.opendns.com  #opendns
        #- tls://dns.google:853 #谷歌
        #- https://dns.google/dns-query
        - https://8.8.8.8/dns-query
        #- tls://1.1.1.1:853 #cloudflare
        #- https://cloudflare-dns.com/dns-query
        - https://1.1.1.1/dns-query
        #- tls://dns.rubyfish.cn:853  #红鱼
        - https://dns.rubyfish.cn/dns-query
        #- tls://223.5.5.5:853 #alidns
        - https://223.5.5.5/dns-query
        #- tls://dns.quad9.net:853 #qurd9
        #- https://dns.quad9.net/dns-query
        - https://9.9.9.9/dns-query
      fallback-filter:
        geoip: true # 默认
        ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
          - 240.0.0.0/4
profileParsersText: |
  parsers: # array
    - reg: .*
      file: 'C:/Users/YOURNAME/.config/clash/parser.yaml'
    - reg: .*
      file: 'C:/Users/YOURNAME/.config/clash/parser.js'
connProfile: true
shortcutSystemProxy: ""
shortcutMixin: ""
connMode: true
showNewVersionIcon: true
systemProxyType: 0
showProxyFilter: true
childProcessText: >
  processes: # array
    # subconvertor
    - command: "C:\\Users\\YOURNAME\\.config\\clash\\subconverter\\subconverter.exe"
      args:
        - "-cfw" # cfw
        - "-f" # 默认配置文件。可被url覆盖
        - "pref-new.yml" # 文件路径
      options:
        cwd: C:\Users\YOURNAME\.config\clash\subconverter # 子进程工作目录
        windowsHide: true # 隐藏子进程的控制台窗口
    # 用于本地代理网易云音乐解锁
    - command: "C:\\Users\\YOURNAME\\.config\\clash\\UnblockNeteaseMusic-windows-amd64\\UnblockNeteaseMusic.exe"
      args:
        - "-l" # log
        - "log.log"  # log路径
        - "-m" # 模式
        - "2"  # 1 为host模式，需要管理员权限，其他为非host模式
        - "-p" # http端口
        - "2223" 
        - "-sp" # https端口
        - "2224"
        #- "-o" # 源: kuwo:酷我(Default), kugou:酷狗, migu:咪咕
        #- "kugou"
        #- "migu"
      options:
        cwd: C:\Users\YOURNAME\.config\clash\UnblockNeteaseMusic-windows-amd64 # 子进程工作目录
        windowsHide: true # 隐藏子进程的控制台窗口
systemProxyTypeIndex: 0
pacContentText: ""
editor: 0
latencyTimeout: 5000
